CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(255) DEFAULT 'user',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP DEFAULT NULL
);
CREATE TABLE addresses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR2(255) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    state VARCHAR2(100) NOT NULL,
    postalCode VARCHAR2(20) NOT NULL,
    country VARCHAR2(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE userAddress (
    userId NUMBER,
    addressId NUMBER,
    PRIMARY KEY (userId, addressId),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (addressId) REFERENCES addresses(id) ON DELETE CASCADE
);
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('John Doe', 'john.doe@example.com', 'password123', 'admin', TIMESTAMP '2023-05-01 12:00:00', TIMESTAMP '2023-05-01 12:00:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Jane Smith', 'jane.smith@example.com', 'password123', 'user', TIMESTAMP '2023-06-15 12:01:00', TIMESTAMP '2023-06-15 12:01:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Alice Brown', 'alice.brown@example.com', 'password123', 'user', TIMESTAMP '2023-07-10 12:02:00', TIMESTAMP '2023-07-10 12:02:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Bob Johnson', 'bob.johnson@example.com', 'password123', 'guest', TIMESTAMP '2023-08-20 12:03:00', TIMESTAMP '2023-08-20 12:03:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Charlie White', 'charlie.white@example.com', 'password123', 'user', TIMESTAMP '2023-09-05 12:04:00', TIMESTAMP '2023-09-05 12:04:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Daisy Green', 'daisy.green@example.com', 'password123', 'user', TIMESTAMP '2023-10-01 12:05:00', TIMESTAMP '2023-10-01 12:05:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Edward Black', 'edward.black@example.com', 'password123', 'admin', TIMESTAMP '2023-11-10 12:06:00', TIMESTAMP '2023-11-10 12:06:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Fiona Gray', 'fiona.gray@example.com', 'password123', 'guest', TIMESTAMP '2023-12-01 12:07:00', TIMESTAMP '2023-12-01 12:07:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('George Blue', 'george.blue@example.com', 'password123', 'user', TIMESTAMP '2023-12-03 12:08:00', TIMESTAMP '2023-12-03 12:08:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Hannah Yellow', 'hannah.yellow@example.com', 'password123', 'user', TIMESTAMP '2023-12-05 12:09:00', TIMESTAMP '2023-12-05 12:09:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Ian Orange', 'ian.orange@example.com', 'password123', 'user', TIMESTAMP '2023-12-07 12:10:00', TIMESTAMP '2023-12-07 12:10:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Jenny Red', 'jenny.red@example.com', 'password123', 'guest', TIMESTAMP '2023-12-09 12:11:00', TIMESTAMP '2023-12-09 12:11:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Kyle Brown', 'kyle.brown@example.com', 'password123', 'admin', TIMESTAMP '2023-11-15 12:12:00', TIMESTAMP '2023-11-15 12:12:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Lara Purple', 'lara.purple@example.com', 'password123', 'user', TIMESTAMP '2023-10-20 12:13:00', TIMESTAMP '2023-10-20 12:13:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Mike Silver', 'mike.silver@example.com', 'password123', 'user', TIMESTAMP '2023-09-25 12:14:00', TIMESTAMP '2023-09-25 12:14:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Nina Gold', 'nina.gold@example.com', 'password123', 'user', TIMESTAMP '2023-08-10 12:15:00', TIMESTAMP '2023-08-10 12:15:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Oscar Pink', 'oscar.pink@example.com', 'password123', 'guest', TIMESTAMP '2023-07-15 12:16:00', TIMESTAMP '2023-07-15 12:16:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Paula Lime', 'paula.lime@example.com', 'password123', 'user', TIMESTAMP '2023-06-01 12:17:00', TIMESTAMP '2023-06-01 12:17:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Quinn Cyan', 'quinn.cyan@example.com', 'password123', 'user', TIMESTAMP '2023-05-10 12:18:00', TIMESTAMP '2023-05-10 12:18:00');
INSERT INTO users (name, email, password, role, createdAt, updatedAt) VALUES ('Rachel Teal', 'rachel.teal@example.com', 'password123', 'user', TIMESTAMP '2023-04-20 12:19:00', TIMESTAMP '2023-04-20 12:19:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('123 Maple St', 'Springfield', 'IL', '62701', 'USA', TIMESTAMP '2023-05-01 12:00:00', TIMESTAMP '2023-05-01 12:00:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('456 Oak St', 'Springfield', 'IL', '62701', 'USA', TIMESTAMP '2023-06-15 12:01:00', TIMESTAMP '2023-06-15 12:01:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('789 Pine St', 'Chicago', 'IL', '60601', 'USA', TIMESTAMP '2023-07-10 12:02:00', TIMESTAMP '2023-07-10 12:02:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('321 Birch St', 'New York', 'NY', '10001', 'USA', TIMESTAMP '2023-08-20 12:03:00', TIMESTAMP '2023-08-20 12:03:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('654 Cedar St', 'Los Angeles', 'CA', '90001', 'USA', TIMESTAMP '2023-09-05 12:04:00', TIMESTAMP '2023-09-05 12:04:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('987 Elm St', 'Houston', 'TX', '77001', 'USA', TIMESTAMP '2023-10-01 12:05:00', TIMESTAMP '2023-10-01 12:05:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('111 Walnut St', 'Phoenix', 'AZ', '85001', 'USA', TIMESTAMP '2023-11-10 12:06:00', TIMESTAMP '2023-11-10 12:06:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('222 Ash St', 'Philadelphia', 'PA', '19101', 'USA', TIMESTAMP '2023-12-01 12:07:00', TIMESTAMP '2023-12-01 12:07:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('333 Beech St', 'San Antonio', 'TX', '78201', 'USA', TIMESTAMP '2023-12-03 12:08:00', TIMESTAMP '2023-12-03 12:08:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('444 Cherry St', 'Dallas', 'TX', '75201', 'USA', TIMESTAMP '2023-12-05 12:09:00', TIMESTAMP '2023-12-05 12:09:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('555 Fir St', 'San Diego', 'CA', '92101', 'USA', TIMESTAMP '2023-12-07 12:10:00', TIMESTAMP '2023-12-07 12:10:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('666 Hemlock St', 'San Jose', 'CA', '95101', 'USA', TIMESTAMP '2023-12-09 12:11:00', TIMESTAMP '2023-12-09 12:11:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('777 Holly St', 'Austin', 'TX', '73301', 'USA', TIMESTAMP '2023-12-11 12:12:00', TIMESTAMP '2023-12-11 12:12:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('888 Ivy St', 'Jacksonville', 'FL', '32099', 'USA', TIMESTAMP '2023-12-13 12:13:00', TIMESTAMP '2023-12-13 12:13:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('999 Juniper St', 'Columbus', 'OH', '43085', 'USA', TIMESTAMP '2023-12-15 12:14:00', TIMESTAMP '2023-12-15 12:14:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('101 Sycamore St', 'Charlotte', 'NC', '28201', 'USA', TIMESTAMP '2023-12-17 12:15:00', TIMESTAMP '2023-12-17 12:15:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('102 Maplewood St', 'Detroit', 'MI', '48201', 'USA', TIMESTAMP '2023-12-19 12:16:00', TIMESTAMP '2023-12-19 12:16:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('103 Magnolia St', 'El Paso', 'TX', '79901', 'USA', TIMESTAMP '2023-12-21 12:17:00', TIMESTAMP '2023-12-21 12:17:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('104 Linden St', 'Boston', 'MA', '02108', 'USA', TIMESTAMP '2023-12-23 12:18:00', TIMESTAMP '2023-12-23 12:18:00');
INSERT INTO addresses (street, city, state, postalCode, country, createdAt, updatedAt) VALUES ('105 Palm St', 'Denver', 'CO', '80201', 'USA', TIMESTAMP '2023-12-25 12:19:00', TIMESTAMP '2023-12-25 12:19:00');
INSERT INTO userAddress (userId, addressId) VALUES (1, 1);
INSERT INTO userAddress (userId, addressId) VALUES (2, 2);
INSERT INTO userAddress (userId, addressId) VALUES (3, 3);
INSERT INTO userAddress (userId, addressId) VALUES (4, 4);
INSERT INTO userAddress (userId, addressId) VALUES (5, 5);
INSERT INTO userAddress (userId, addressId) VALUES (6, 6);
INSERT INTO userAddress (userId, addressId) VALUES (7, 7);
INSERT INTO userAddress (userId, addressId) VALUES (8, 8);
INSERT INTO userAddress (userId, addressId) VALUES (9, 9);
INSERT INTO userAddress (userId, addressId) VALUES (10, 10);
INSERT INTO userAddress (userId, addressId) VALUES (11, 11);
INSERT INTO userAddress (userId, addressId) VALUES (12, 12);
INSERT INTO userAddress (userId, addressId) VALUES (13, 13);
INSERT INTO userAddress (userId, addressId) VALUES (14, 14);
INSERT INTO userAddress (userId, addressId) VALUES (15, 15);
INSERT INTO userAddress (userId, addressId) VALUES (16, 16);
INSERT INTO userAddress (userId, addressId) VALUES (17, 17);
INSERT INTO userAddress (userId, addressId) VALUES (18, 18);
INSERT INTO userAddress (userId, addressId) VALUES (19, 19);
INSERT INTO userAddress (userId, addressId) VALUES (20, 20);
